import type { StockQuote } from "@/lib/market-types";

// Illustrative company universe for educational demo purposes. Prices and
// changes are seeded, deterministic mock values — NOT live market data.
// Swap this module for a real provider (Alpha Vantage / Twelve Data) by
// implementing the same StockQuote[] shape in lib/providers/market-data.ts.

export const MOCK_STOCKS: StockQuote[] = [
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy", price: 2934.5, change: 34.2, changePercent: 1.18, volume: 5_231_000, marketCap: 1_985_000 },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT", price: 3812.75, change: -14.6, changePercent: -0.38, volume: 1_842_000, marketCap: 1_390_000 },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking", price: 1652.3, change: 10.15, changePercent: 0.62, volume: 8_120_000, marketCap: 1_255_000 },
  { symbol: "INFY", name: "Infosys", sector: "IT", price: 1489.2, change: -15.75, changePercent: -1.05, volume: 3_045_000, marketCap: 618_000 },
  { symbol: "ITC", name: "ITC Limited", sector: "FMCG", price: 438.6, change: 0.85, changePercent: 0.19, volume: 6_732_000, marketCap: 546_000 },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", price: 812.45, change: 16.9, changePercent: 2.12, volume: 12_400_000, marketCap: 724_000 },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom", price: 1524.1, change: 7.1, changePercent: 0.47, volume: 2_910_000, marketCap: 913_000 },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Infrastructure", price: 3641.9, change: -8.2, changePercent: -0.22, volume: 1_205_000, marketCap: 501_000 },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer Goods", price: 2891.35, change: -42.1, changePercent: -1.44, volume: 812_000, marketCap: 277_000 },
  { symbol: "MARUTI", name: "Maruti Suzuki", sector: "Automobile", price: 12_845.0, change: 210.5, changePercent: 1.67, volume: 421_000, marketCap: 388_000 },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Pharma", price: 1698.8, change: 24.3, changePercent: 1.45, volume: 1_530_000, marketCap: 407_000 },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals", price: 168.25, change: -3.9, changePercent: -2.27, volume: 24_800_000, marketCap: 210_000 },
  { symbol: "WIPRO", name: "Wipro", sector: "IT", price: 542.15, change: -6.8, changePercent: -1.24, volume: 4_120_000, marketCap: 283_000 },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking", price: 1187.6, change: 19.4, changePercent: 1.66, volume: 5_640_000, marketCap: 366_000 },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Infrastructure", price: 1432.9, change: 38.75, changePercent: 2.78, volume: 3_310_000, marketCap: 308_000 },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", sector: "FMCG", price: 2456.4, change: -18.6, changePercent: -0.75, volume: 940_000, marketCap: 577_000 },
  { symbol: "NTPC", name: "NTPC Limited", sector: "Power", price: 358.7, change: 5.35, changePercent: 1.51, volume: 9_870_000, marketCap: 348_000 },
  { symbol: "ONGC", name: "Oil & Natural Gas Corp", sector: "Energy", price: 246.15, change: -2.1, changePercent: -0.85, volume: 11_200_000, marketCap: 309_000 },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer Goods", price: 3298.5, change: 56.9, changePercent: 1.76, volume: 680_000, marketCap: 293_000 },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking", price: 1789.25, change: -9.4, changePercent: -0.52, volume: 2_450_000, marketCap: 355_000 },
];

export const MOCK_INDICES = [
  { name: "NIFTY 50", value: 24_812.35, change: 142.6, changePercent: 0.58 },
  { name: "SENSEX", value: 81_643.2, change: 398.15, changePercent: 0.49 },
  { name: "NIFTY BANK", value: 52_104.8, change: -86.4, changePercent: -0.17 },
  { name: "NIFTY IT", value: 40_218.6, change: -312.9, changePercent: -0.77 },
];

export const MOCK_NEWS = [
  {
    id: "n1",
    headline: "Reliance Industries expands green energy investment plans",
    source: "Business Standard",
    publishedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    relatedSymbol: "RELIANCE",
    summary: "The company outlined further capital allocation toward renewable energy projects as part of its long-term diversification strategy.",
  },
  {
    id: "n2",
    headline: "IT sector faces margin pressure amid global demand slowdown",
    source: "Economic Times",
    publishedAt: new Date(Date.now() - 1000 * 60 * 105).toISOString(),
    relatedSymbol: "INFY",
    summary: "Analysts note that discretionary tech spending from key overseas clients has softened, weighing on near-term revenue guidance across the sector.",
  },
  {
    id: "n3",
    headline: "Banking stocks rally on stable credit growth data",
    source: "Mint",
    publishedAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    relatedSymbol: "SBIN",
    summary: "Sector-wide credit growth figures released this week came in ahead of expectations, lifting sentiment across major lenders.",
  },
  {
    id: "n4",
    headline: "Auto sector sees strong festive-season demand signals",
    source: "Moneycontrol",
    publishedAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    relatedSymbol: "MARUTI",
    summary: "Dealers report healthy booking volumes ahead of the festive quarter, with passenger vehicle demand outperforming prior-year trends.",
  },
  {
    id: "n5",
    headline: "Metals stocks slip on softer global commodity prices",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    relatedSymbol: "TATASTEEL",
    summary: "A pullback in international steel and iron ore prices weighed on domestic metals producers in early trade.",
  },
  {
    id: "n6",
    headline: "TCS wins $600M digital transformation deal with UK bank",
    source: "Business Today",
    publishedAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    relatedSymbol: "TCS",
    summary: "Tata Consultancy Services secured a multi-year engagement to modernize a major UK bank's core systems, boosting order book visibility.",
  },
  {
    id: "n7",
    headline: "HDFC Bank's deposit growth outpaces credit expansion",
    source: "Financial Express",
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    relatedSymbol: "HDFCBANK",
    summary: "Post-merger deposit mobilization strategies are showing results, with CASA ratio stabilizing ahead of management guidance.",
  },
  {
    id: "n8",
    headline: "Sun Pharma receives FDA approval for new specialty drug",
    source: "Livemint",
    publishedAt: new Date(Date.now() - 1000 * 60 * 250).toISOString(),
    relatedSymbol: "SUNPHARMA",
    summary: "The US FDA approved Sun Pharmaceutical's new dermatology product, expanding its specialty portfolio in the American market.",
  },
  {
    id: "n9",
    headline: "Bharti Airtel's 5G subscriber base crosses 100 million",
    source: "NDTV",
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    relatedSymbol: "BHARTIARTL",
    summary: "Airtel's rapid 5G rollout continues to convert users from legacy networks, with management reiterating premium ARPU growth targets.",
  },
  {
    id: "n10",
    headline: "Asian Paints faces competitive pricing pressure in decorative segment",
    source: "CNBC-TV18",
    publishedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    relatedSymbol: "ASIANPAINT",
    summary: "Emerging paint brands backed by FMCG companies are intensifying competition, leading to margin concerns for the market leader.",
  },
  {
    id: "n11",
    headline: "Wipro announces AI-first strategy, plans 10,000 reskilling",
    source: "Economic Times",
    publishedAt: new Date(Date.now() - 1000 * 60 * 540).toISOString(),
    relatedSymbol: "WIPRO",
    summary: "Wipro's new CEO outlined a company-wide pivot toward generative AI services, with significant investment in employee upskilling programs.",
  },
  {
    id: "n12",
    headline: "Titan Company's jewellery division posts record quarterly revenue",
    source: "Moneycontrol",
    publishedAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    relatedSymbol: "TITAN",
    summary: "Tanishq's same-store growth and new store additions drove jewellery segment revenue to an all-time quarterly high.",
  },
  {
    id: "n13",
    headline: "Axis Bank's digital transactions grow 45% year-on-year",
    source: "Business Standard",
    publishedAt: new Date(Date.now() - 1000 * 60 * 680).toISOString(),
    relatedSymbol: "AXISBANK",
    summary: "The bank's digital channels now handle over 85% of all transactions, reducing operating costs while improving customer engagement.",
  },
  {
    id: "n14",
    headline: "NTPC commissions 2 GW solar power plant in Rajasthan",
    source: "Mint",
    publishedAt: new Date(Date.now() - 1000 * 60 * 780).toISOString(),
    relatedSymbol: "NTPC",
    summary: "India's largest power producer added to its renewable capacity, on track to meet its 60 GW green energy target by 2032.",
  },
  {
    id: "n15",
    headline: "Adani Ports acquires new container terminal in Sri Lanka",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 1000 * 60 * 850).toISOString(),
    relatedSymbol: "ADANIPORTS",
    summary: "The acquisition strengthens Adani's Indian Ocean port network, adding 3 million TEU annual capacity to the group.",
  },
  {
    id: "n16",
    headline: "ITC's FMCG business achieves profitability milestone",
    source: "Economic Times",
    publishedAt: new Date(Date.now() - 1000 * 60 * 920).toISOString(),
    relatedSymbol: "ITC",
    summary: "After years of investment, ITC's FMCG segment hit a 10% EBITDA margin, signaling the business has reached sustainable profitability.",
  },
  {
    id: "n17",
    headline: "L&T wins ₹12,000 crore order for Middle East metro project",
    source: "Business Today",
    publishedAt: new Date(Date.now() - 1000 * 60 * 1020).toISOString(),
    relatedSymbol: "LT",
    summary: "Larsen & Toubro's international infrastructure order book received a major boost with this multi-year transit construction contract.",
  },
  {
    id: "n18",
    headline: "ONGC raises domestic natural gas production by 8%",
    source: "Financial Express",
    publishedAt: new Date(Date.now() - 1000 * 60 * 1150).toISOString(),
    relatedSymbol: "ONGC",
    summary: "Enhanced recovery techniques at existing wells and new offshore discoveries are driving production gains for the national oil company.",
  },
  {
    id: "n19",
    headline: "Kotak Mahindra Bank expands wealth management with fintech acquisition",
    source: "Livemint",
    publishedAt: new Date(Date.now() - 1000 * 60 * 1280).toISOString(),
    relatedSymbol: "KOTAKBANK",
    summary: "The acquisition of a robo-advisory startup will bolster Kotak's digital wealth management offerings for mass-affluent clients.",
  },
  {
    id: "n20",
    headline: "HUL launches premium D2C platform to counter new-age brands",
    source: "CNBC-TV18",
    publishedAt: new Date(Date.now() - 1000 * 60 * 1400).toISOString(),
    relatedSymbol: "HINDUNILVR",
    summary: "Hindustan Unilever's direct-to-consumer digital storefront aims to capture premium consumers and gain first-party data insights.",
  },
];

export const MOCK_WATCHLIST_SYMBOLS = ["RELIANCE", "TCS", "SBIN", "TITAN"];
